GET http://localhost:3000/?ad=4 HTTP/1.1

########
POST http://localhost:3000/?a=5 HTTP/1.1
Content-Type: application/json

{
    "a": 5,
    "b" : 10
    
}


// this file is based on restful extension in vscoded. its just for developing and let us use vscode instead of chrome. we do not need to upload this file in final proj.